### ISSUE TITLE
вопрос по верстке

### ISSUE THREAD

**Issue by maxkadushkin** [mrneyron/test1#3]
![image](https://user-images.githubusercontent.com/17923696/118559048-16b34680-b770-11eb-942d-663b075d7315.png)
так выглядит хорошо
![image](https://user-images.githubusercontent.com/17923696/118559291-61cd5980-b770-11eb-908e-728bbb836573.png)
а так центрирования кнопок не хватает

такой же вид на других экранах

**Comment by shinenkov** [comment]
Сделал так специально. Изменить можно вынести условие "openScientific" за Grid item ( 230 и 232 строка Calculator.js).
Сейчас править код не могу
